export enum Role {
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCT = 'GET_PRODUCT',
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  CREATE_SHIPMENT = 'CREATE_SHIPMENT',
}
